Repository auth0/JWTDecode.Android, pull requests merged in 2018-11, with the labels that each got.

#30 Target SDK 28. Update Wrapper and OSS plugin
  .circleci/config.yml
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  lib/build.gradle
Labels: CH: Changed

#15 Allow JWT with empty Signatures
  lib/src/main/java/com/auth0/android/jwt/JWT.java
  lib/src/test/java/com/auth0/android/jwt/JWTTest.java
Labels: CH: Fixed

#31 Allow to obtain the Map of Claims
  .circleci/config.yml
  README.md
  lib/src/main/java/com/auth0/android/jwt/JWT.java
  lib/src/main/java/com/auth0/android/jwt/JWTPayload.java
  lib/src/test/java/com/auth0/android/jwt/JWTTest.java
Labels: CH: Added
